// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIDevSecOps.Context;

#nullable disable

namespace WebAPIDevSecOps.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711171954_AddTokenBlacklistTable")]
    partial class AddTokenBlacklistTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDevSecOps.Models.EmpCatTipoEmpleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("strDescripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("strValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("EmpCatTipoEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.EmpEmpleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("idEmpCatTipoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("strAMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strAPaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strCURP")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("strNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idEmpCatTipoEmpleado");

                    b.HasIndex("strCURP")
                        .IsUnique()
                        .HasFilter("[strCURP] IS NOT NULL");

                    b.ToTable("EmpEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.SegTokenBlacklist", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiryUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Jti");

                    b.ToTable("SegTokenBlacklist");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.SegUsuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("dteFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("strCorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strPWD")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("id");

                    b.HasIndex("strNombre")
                        .IsUnique();

                    b.ToTable("SegUsuario");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.EmpEmpleado", b =>
                {
                    b.HasOne("WebAPIDevSecOps.Models.EmpCatTipoEmpleado", "EmpCatTipoEmpleado")
                        .WithMany()
                        .HasForeignKey("idEmpCatTipoEmpleado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmpCatTipoEmpleado");
                });
#pragma warning restore 612, 618
        }
    }
}
