// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIDevSecOps.Context;

#nullable disable

namespace WebAPIDevSecOps.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714185913_V2_AddTables")]
    partial class V2_AddTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDevSecOps.Models.CliCliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("strCorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("strDireccionCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("strNombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("strNumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.HasIndex("strCorreoElectronico")
                        .IsUnique()
                        .HasDatabaseName("IX_CliCliente_strCorreoElectronico");

                    b.HasIndex("strNombreCliente")
                        .HasDatabaseName("IX_CliCliente_strNombreCliente");

                    b.ToTable("CliCliente");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.EmpCatTipoEmpleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("strDescripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("strValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("EmpCatTipoEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.EmpEmpleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("idEmpCatTipoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("strAMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strAPaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strCURP")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("strNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idEmpCatTipoEmpleado");

                    b.HasIndex("strCURP")
                        .IsUnique()
                        .HasFilter("[strCURP] IS NOT NULL");

                    b.ToTable("EmpEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.ProProducto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("intNumeroExistencia")
                        .HasColumnType("int");

                    b.Property<string>("strDescripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("strNombreProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strURLImagen")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("id");

                    b.HasIndex("strNombreProducto")
                        .HasDatabaseName("IX_ProProducto_strNombreProducto");

                    b.ToTable("ProProducto");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.SegTokenBlacklist", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiryUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Jti");

                    b.ToTable("SegTokenBlacklist", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.SegUsuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("dteFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("strCorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strPWD")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("id");

                    b.HasIndex("strNombre")
                        .IsUnique();

                    b.ToTable("SegUsuario");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.VenCatEstado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("strDescripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("strValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("VenCatEstado");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.VenVenta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("dteFechaHoraCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCliCliente")
                        .HasColumnType("int");

                    b.Property<int>("idSegUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idVenCatEstado")
                        .HasColumnType("int");

                    b.Property<string>("strClaveVenta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.HasIndex("dteFechaHoraCompra")
                        .HasDatabaseName("IX_VenVenta_dteFechaHoraCompra");

                    b.HasIndex("idCliCliente");

                    b.HasIndex("idSegUsuario");

                    b.HasIndex("idVenCatEstado");

                    b.HasIndex("strClaveVenta")
                        .IsUnique()
                        .HasDatabaseName("IX_VenVenta_strClaveVenta");

                    b.ToTable("VenVenta");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.VenVentaDetalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decTotalVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idProProducto")
                        .HasColumnType("int");

                    b.Property<int>("idVenVenta")
                        .HasColumnType("int");

                    b.Property<int>("intPiezaVenta")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idProProducto");

                    b.HasIndex("idVenVenta");

                    b.ToTable("VenVentaDetalle");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.EmpEmpleado", b =>
                {
                    b.HasOne("WebAPIDevSecOps.Models.EmpCatTipoEmpleado", "EmpCatTipoEmpleado")
                        .WithMany()
                        .HasForeignKey("idEmpCatTipoEmpleado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmpCatTipoEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.VenVenta", b =>
                {
                    b.HasOne("WebAPIDevSecOps.Models.CliCliente", "CliCliente")
                        .WithMany()
                        .HasForeignKey("idCliCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPIDevSecOps.Models.SegUsuario", "SegUsuario")
                        .WithMany()
                        .HasForeignKey("idSegUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPIDevSecOps.Models.VenCatEstado", "VenCatEstado")
                        .WithMany()
                        .HasForeignKey("idVenCatEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CliCliente");

                    b.Navigation("SegUsuario");

                    b.Navigation("VenCatEstado");
                });

            modelBuilder.Entity("WebAPIDevSecOps.Models.VenVentaDetalle", b =>
                {
                    b.HasOne("WebAPIDevSecOps.Models.ProProducto", "ProProducto")
                        .WithMany()
                        .HasForeignKey("idProProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPIDevSecOps.Models.VenVenta", "VenVenta")
                        .WithMany()
                        .HasForeignKey("idVenVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProProducto");

                    b.Navigation("VenVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
